name: cifuzz

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
    - '*-ci'

jobs:
  fuzzing:
    if: github.repository == 'Yubico/libfido2'
    runs-on: ubuntu-20.04
    steps:
    - name: build fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        oss-fuzz-project-name: 'libfido2'
        dry-run: false
    - name: run fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        oss-fuzz-project-name: 'libfido2'
        fuzz-seconds: 600
        dry-run: false
    - name: upload crash
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: artifacts
        path: ./out/artifacts
